GET http://localhost:4000

###

POST http://localhost:4000/register
Content-Type: application/json

{
    "name": "Amal1",
    "email": "amal1@test.com",
    "password": "1234"
}

###

POST http://localhost:4000/signin
Content-Type: application/json

{
    "email": "amal1@test.com",
    "password": "1234"
}

###

GET http://localhost:4000/profile/1

###

PUT http://localhost:4000/image
Content-Type: application/json

{
    "id": "2"
}